// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrganizacijaDogadjajaApp.UcesniciAPI.Data;

#nullable disable

namespace OrganizacijaDogadjajaApp.UcesniciAPI.Migrations
{
    [DbContext(typeof(UcesniciDbContext))]
    partial class UcesniciDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OrganizacijaDogadjajaApp.UcesniciAPI.Entities.DogadjajReferenca", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AgendaDogadjaja")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatumIVreme")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DogadjajId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NazivDogadjaja")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WelcomeMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DogadjajId")
                        .IsUnique();

                    b.ToTable("DogadjajiReference");
                });

            modelBuilder.Entity("OrganizacijaDogadjajaApp.UcesniciAPI.Entities.ProcessedMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ProcessedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.ToTable("ProcessedMessages");
                });

            modelBuilder.Entity("OrganizacijaDogadjajaApp.UcesniciAPI.Models.Prijava", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DatumPrijave")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DogadjajId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UcesnikId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UcesnikId");

                    b.ToTable("Prijave");
                });

            modelBuilder.Entity("OrganizacijaDogadjajaApp.UcesniciAPI.Models.SagaPrijava", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DatumPrijave")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DogadjajId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Otkazana")
                        .HasColumnType("bit");

                    b.Property<Guid>("RezervacijaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UcesnikId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("SagaPrijave");
                });

            modelBuilder.Entity("OrganizacijaDogadjajaApp.UcesniciAPI.Models.Ucesnik", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ucesnici");
                });

            modelBuilder.Entity("OrganizacijaDogadjajaApp.UcesniciAPI.Models.Prijava", b =>
                {
                    b.HasOne("OrganizacijaDogadjajaApp.UcesniciAPI.Models.Ucesnik", "Ucesnik")
                        .WithMany("Prijave")
                        .HasForeignKey("UcesnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ucesnik");
                });

            modelBuilder.Entity("OrganizacijaDogadjajaApp.UcesniciAPI.Models.Ucesnik", b =>
                {
                    b.Navigation("Prijave");
                });
#pragma warning restore 612, 618
        }
    }
}
