// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrganizacijaDogadjajaApp.Data;

#nullable disable

namespace OrganizacijaDogadjajaApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260505172637_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OrganizacijaDogadjajaApp.Models.Dogadjaj", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AgendaDogadjaja")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CenaKotizacije")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DatumIVreme")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LokacijaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NazivDogadjaja")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TipDogadjajaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Trajanje")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LokacijaId");

                    b.HasIndex("TipDogadjajaId");

                    b.ToTable("Dogadjaji");
                });

            modelBuilder.Entity("OrganizacijaDogadjajaApp.Models.Lokacija", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Kapacitet")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Lokacije");
                });

            modelBuilder.Entity("OrganizacijaDogadjajaApp.Models.Predavac", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OblastStrucnosti")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Predavaci");
                });

            modelBuilder.Entity("OrganizacijaDogadjajaApp.Models.Predavanje", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DogadjajId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Pocetak")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PredavacId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Tema")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrajanjePredavanja")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DogadjajId");

                    b.HasIndex("PredavacId");

                    b.ToTable("Predavanja");
                });

            modelBuilder.Entity("OrganizacijaDogadjajaApp.Models.Prijava", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DatumPrijave")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DogadjajId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UcesnikId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DogadjajId");

                    b.HasIndex("UcesnikId");

                    b.ToTable("Prijave");
                });

            modelBuilder.Entity("OrganizacijaDogadjajaApp.Models.TipDogadjaja", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TipoviDogadjaja");
                });

            modelBuilder.Entity("OrganizacijaDogadjajaApp.Models.Ucesnik", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ucesnici");
                });

            modelBuilder.Entity("OrganizacijaDogadjajaApp.Models.Dogadjaj", b =>
                {
                    b.HasOne("OrganizacijaDogadjajaApp.Models.Lokacija", "Lokacija")
                        .WithMany("Dogadjaji")
                        .HasForeignKey("LokacijaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrganizacijaDogadjajaApp.Models.TipDogadjaja", "TipDogadjaja")
                        .WithMany("Dogadjaji")
                        .HasForeignKey("TipDogadjajaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lokacija");

                    b.Navigation("TipDogadjaja");
                });

            modelBuilder.Entity("OrganizacijaDogadjajaApp.Models.Predavanje", b =>
                {
                    b.HasOne("OrganizacijaDogadjajaApp.Models.Dogadjaj", "Dogadjaj")
                        .WithMany()
                        .HasForeignKey("DogadjajId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrganizacijaDogadjajaApp.Models.Predavac", "Predavac")
                        .WithMany("Predavanja")
                        .HasForeignKey("PredavacId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dogadjaj");

                    b.Navigation("Predavac");
                });

            modelBuilder.Entity("OrganizacijaDogadjajaApp.Models.Prijava", b =>
                {
                    b.HasOne("OrganizacijaDogadjajaApp.Models.Dogadjaj", "Dogadjaj")
                        .WithMany()
                        .HasForeignKey("DogadjajId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrganizacijaDogadjajaApp.Models.Ucesnik", "Ucesnik")
                        .WithMany("Prijave")
                        .HasForeignKey("UcesnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dogadjaj");

                    b.Navigation("Ucesnik");
                });

            modelBuilder.Entity("OrganizacijaDogadjajaApp.Models.Lokacija", b =>
                {
                    b.Navigation("Dogadjaji");
                });

            modelBuilder.Entity("OrganizacijaDogadjajaApp.Models.Predavac", b =>
                {
                    b.Navigation("Predavanja");
                });

            modelBuilder.Entity("OrganizacijaDogadjajaApp.Models.TipDogadjaja", b =>
                {
                    b.Navigation("Dogadjaji");
                });

            modelBuilder.Entity("OrganizacijaDogadjajaApp.Models.Ucesnik", b =>
                {
                    b.Navigation("Prijave");
                });
#pragma warning restore 612, 618
        }
    }
}
