// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrganizacijaDogadjajaApp.DogadjajiAPI.Data;

#nullable disable

namespace OrganizacijaDogadjajaApp.DogadjajiAPI.Migrations
{
    [DbContext(typeof(DogadjajiDbContext))]
    [Migration("20260506081943_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OrganizacijaDogadjajaApp.DogadjajiAPI.Models.Dogadjaj", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AgendaDogadjaja")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CenaKotizacije")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DatumIVreme")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LokacijaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NazivDogadjaja")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TipDogadjajaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Trajanje")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LokacijaId");

                    b.HasIndex("TipDogadjajaId");

                    b.ToTable("Dogadjaji");
                });

            modelBuilder.Entity("OrganizacijaDogadjajaApp.DogadjajiAPI.Models.Lokacija", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Kapacitet")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Lokacije");
                });

            modelBuilder.Entity("OrganizacijaDogadjajaApp.DogadjajiAPI.Models.TipDogadjaja", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TipoviDogadjaja");
                });

            modelBuilder.Entity("OrganizacijaDogadjajaApp.DogadjajiAPI.Models.Dogadjaj", b =>
                {
                    b.HasOne("OrganizacijaDogadjajaApp.DogadjajiAPI.Models.Lokacija", "Lokacija")
                        .WithMany("Dogadjaji")
                        .HasForeignKey("LokacijaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrganizacijaDogadjajaApp.DogadjajiAPI.Models.TipDogadjaja", "TipDogadjaja")
                        .WithMany("Dogadjaji")
                        .HasForeignKey("TipDogadjajaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lokacija");

                    b.Navigation("TipDogadjaja");
                });

            modelBuilder.Entity("OrganizacijaDogadjajaApp.DogadjajiAPI.Models.Lokacija", b =>
                {
                    b.Navigation("Dogadjaji");
                });

            modelBuilder.Entity("OrganizacijaDogadjajaApp.DogadjajiAPI.Models.TipDogadjaja", b =>
                {
                    b.Navigation("Dogadjaji");
                });
#pragma warning restore 612, 618
        }
    }
}
