// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrganizacijaDogadjajaApp.PredavanjaAPI.Data;

#nullable disable

namespace OrganizacijaDogadjajaApp.PredavanjaAPI.Migrations
{
    [DbContext(typeof(PredavanjaDbContext))]
    partial class PredavanjaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OrganizacijaDogadjajaApp.PredavanjaAPI.Entities.ProcessedMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ProcessedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.ToTable("ProcessedMessages");
                });

            modelBuilder.Entity("OrganizacijaDogadjajaApp.PredavanjaAPI.Models.Predavac", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OblastStrucnosti")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Predavaci");
                });

            modelBuilder.Entity("OrganizacijaDogadjajaApp.PredavanjaAPI.Models.Predavanje", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DogadjajId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Pocetak")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PredavacId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Tema")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrajanjePredavanja")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PredavacId");

                    b.ToTable("Predavanja");
                });

            modelBuilder.Entity("OrganizacijaDogadjajaApp.PredavanjaAPI.Models.SagaRaspored", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DogadjajId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("KreiranaU")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Obrisan")
                        .HasColumnType("bit");

                    b.Property<Guid>("UcesnikId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("SagaRasporedi");
                });

            modelBuilder.Entity("OrganizacijaDogadjajaApp.PredavanjaAPI.Models.Predavanje", b =>
                {
                    b.HasOne("OrganizacijaDogadjajaApp.PredavanjaAPI.Models.Predavac", "Predavac")
                        .WithMany("Predavanja")
                        .HasForeignKey("PredavacId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Predavac");
                });

            modelBuilder.Entity("OrganizacijaDogadjajaApp.PredavanjaAPI.Models.Predavac", b =>
                {
                    b.Navigation("Predavanja");
                });
#pragma warning restore 612, 618
        }
    }
}
