// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrganizacijaDogadjajaApp.SagaOrchestrator.Data;

#nullable disable

namespace OrganizacijaDogadjajaApp.SagaOrchestrator.Migrations
{
    [DbContext(typeof(SagaDbContext))]
    partial class SagaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OrganizacijaDogadjajaApp.SagaOrchestrator.Entities.SagaInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AzuriranjaU")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentStep")
                        .HasColumnType("int");

                    b.Property<Guid>("DogadjajId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GreskaOpis")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("KreiranaU")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("PrijavaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RasporedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RezervacijaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("UcesnikId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DogadjajId");

                    b.HasIndex("Status");

                    b.ToTable("SagaInstances");
                });
#pragma warning restore 612, 618
        }
    }
}
